src/objects/Solution.object
<CustomObject>
    <fields>
        <fullName>SolutionSpanish__c</fullName>
        <description>Solution auto-translated into Spanish</description>
        <label>SolutionSpanish</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TranslationPending__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates this record has a translation pending</description>
        <inlineHelpText>Indicates this record has a translation pending</inlineHelpText>
        <label>TranslationPending</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/classes/GoingAsync3.cls
public without sharing class GoingAsync3 
	implements queueable, Database.AllowsCallouts {

 	public void execute(QueueableContext context)
    {
    	if(!AppConfigSupport.appEnabled) return; // On/off switch
    	
    	Integer allowedCallouts = 
    		Limits.getLimitCallouts() - Limits.getCallouts();
   		
		if(allowedCallouts<=0) return;
		List<Solution> solutionsToUpdate = 
			[SELECT ID, SolutionNote, SolutionSpanish__c 
			from Solution 
			where LastModifiedDate > :DateTime.Now().addHours(-24) 
			And TranslationPending__c = true LIMIT :allowedCallouts];
		for(Solution sl: solutionsToUpdate)
		{
			sl.SolutionSpanish__c = 
				SimulatedTranslator.translate(sl.SolutionNote);
			sl.TranslationPending__c = false;
		}
		update solutionsToUpdate;
		
		
		if(solutionsToUpdate.size()== allowedCallouts &&
			Limits.getLimitQueueableJobs() - Limits.getQueueableJobs() > 0)
			try
			{
				system.enqueueJob(new GoingAsync3());
			} catch(Exception ex)
			{
				// Alternate chaining mechanism
			}
		
    }
    
    
}